require("busted.runner")()
local mod = require("roomBot.robotTracker")


describe("robotTracker", function()
    local fakeRobot = {}
    setmetatable(fakeRobot, {__index=function(t, k)
        return function() return true end
    end})
    local function check(t, x, y, z, rot)
        assert.are_same({x, y, z}, {t.getPosition()})
        assert.is_equal(rot, t.getRotation())
    end

    it("up down", function()
        local t = mod.createTracker(fakeRobot)
        check(t, 0, 0, 0, "Y+")
        t.up()
        check(t, 0, 0, 1, "Y+")
        t.down()
        check(t, 0, 0, 0, "Y+")
        t.down()
        check(t, 0, 0, -1, "Y+")
    end)
    it("forward back", function()
        local t = mod.createTracker(fakeRobot)
        check(t, 0, 0, 0, "Y+")
        t.forward()
        check(t, 0, 1, 0, "Y+")
        t.back()
        check(t, 0, 0, 0, "Y+")
        t.back()
        check(t, 0, -1, 0, "Y+")
    end)
    it("turnLeft and move", function()
        local t = mod.createTracker(fakeRobot)
        check(t, 0, 0, 0, "Y+")
        t.turnLeft()
        t.forward()
        check(t, -1, 0, 0, "X-")
        t.turnLeft()
        t.forward()
        check(t, -1, -1, 0, "Y-")
        t.turnLeft()
        t.forward()
        check(t, 0, -1, 0, "X+")
        t.turnLeft()
        t.forward()
        check(t, 0, 0, 0, "Y+")
    end)
end)
